#!/bin/bash

# Auto-Build Environment Setup - File Organization Audit
# Generated by Planner Agent
# This is a READ-ONLY investigation task - no services need to be started

set -e

echo "========================================"
echo "File Organization Audit - Investigation"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

echo ""
echo -e "${GREEN}Environment Setup${NC}"
echo "This is a read-only audit task."
echo "No development services need to be started."
echo ""

# ============================================
# VERIFY PROJECT STRUCTURE
# ============================================

echo "Verifying monorepo structure..."

if [ ! -f "pnpm-workspace.yaml" ]; then
    echo -e "${RED}Error: pnpm-workspace.yaml not found${NC}"
    exit 1
fi

if [ ! -d "packages" ]; then
    echo -e "${RED}Error: packages/ directory not found${NC}"
    exit 1
fi

# Check all 4 expected packages exist
PACKAGES=("database" "server" "shared" "client")
for pkg in "${PACKAGES[@]}"; do
    if [ ! -d "packages/$pkg" ]; then
        echo -e "${RED}Error: packages/$pkg not found${NC}"
        exit 1
    fi
done

echo -e "${GREEN}✓ All 4 packages found (database, server, shared, client)${NC}"

# ============================================
# VERIFY TOOLS AVAILABLE
# ============================================

echo ""
echo "Checking required tools..."

if ! command -v find &> /dev/null; then
    echo -e "${RED}Error: 'find' command not available${NC}"
    exit 1
fi

if ! command -v grep &> /dev/null; then
    echo -e "${RED}Error: 'grep' command not available${NC}"
    exit 1
fi

echo -e "${GREEN}✓ All required tools available${NC}"

# ============================================
# READY TO START AUDIT
# ============================================

echo ""
echo "========================================"
echo "Environment Ready for Audit!"
echo "========================================"
echo ""
echo "Task: Read-only file organization audit"
echo "Packages: database, server, shared, client"
echo "Output: file-organization-audit-report.md"
echo ""
echo -e "${YELLOW}Note: This task will NOT modify any files${NC}"
echo -e "${YELLOW}      Only a report will be generated${NC}"
echo ""
echo "Ready to proceed with implementation..."
echo ""
